### PR TITLE
Improving README file & make cert paths relative path.

### PR DESCRIPTION
**Pull request by ayazali**
* Improving README file.
* Make cert paths relative path. 
* Moving transaction timeout to a variable

### CODE REVIEW

**Review by paguos — APPROVED** [review]
Everything is fine! Can you add the configuring fabric part to the main README.md?

**Comment by ayazali** [comment]
I have already added it in hyperledger-lab subdirectory's README.md 

https://github.com/paguos/blockmark/blob/hyperledger/hyperledger-lab/README.md

**Comment by paguos** [comment]
Yep I saw it, but can you add it to the main README.md pls? 👍 So we have a complete README.md ;)

**Comment by ayazali** [comment]
@paguos ok I have put it there also.

**Pull request merged**
